#!/bin/bash

#Fetch and pull repo
git checkout main
git fetch
git pull

#Login to Registry
doctl registry login

#Pushing image to registry
docker compose -f docker-compose.production.yml pull
docker compose -f docker-compose.production.yml up -d

#For more details: https://docs.digitalocean.com/products/container-registry/quickstart/