#!/bin/bash

#Login to Registry
doctl registry login

#Pushing image to registry
docker compose -f docker-compose.production.yml pull
docker-compose -f docker-compose.production.yml up

#For more details: https://docs.digitalocean.com/products/container-registry/quickstart/