# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from photo_portfolio.models.base_model_ import Model
from photo_portfolio import util


class IdSubpageSectionBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, alias: str=None, value: Dict=None):  # noqa: E501
        """IdSubpageSectionBody - a model defined in Swagger

        :param alias: The alias of this IdSubpageSectionBody.  # noqa: E501
        :type alias: str
        :param value: The value of this IdSubpageSectionBody.  # noqa: E501
        :type value: Dict
        """
        self.swagger_types = {
            'alias': str,
            'value': Dict
        }

        self.attribute_map = {
            'alias': 'alias',
            'value': 'value'
        }
        self._alias = alias
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'IdSubpageSectionBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The id_subpage_section_body of this IdSubpageSectionBody.  # noqa: E501
        :rtype: IdSubpageSectionBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def alias(self) -> str:
        """Gets the alias of this IdSubpageSectionBody.

        alias of a section  # noqa: E501

        :return: The alias of this IdSubpageSectionBody.
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias: str):
        """Sets the alias of this IdSubpageSectionBody.

        alias of a section  # noqa: E501

        :param alias: The alias of this IdSubpageSectionBody.
        :type alias: str
        """
        if alias is None:
            raise ValueError("Invalid value for `alias`, must not be `None`")  # noqa: E501

        self._alias = alias

    @property
    def value(self) -> Dict:
        """Gets the value of this IdSubpageSectionBody.

        value of a section  # noqa: E501

        :return: The value of this IdSubpageSectionBody.
        :rtype: Dict
        """
        return self._value

    @value.setter
    def value(self, value: Dict):
        """Sets the value of this IdSubpageSectionBody.

        value of a section  # noqa: E501

        :param value: The value of this IdSubpageSectionBody.
        :type value: Dict
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
