# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from photo_portfolio.models.base_model_ import Model
from photo_portfolio.models.meta_layout import MetaLayout  # noqa: F401,E501
from photo_portfolio.models.meta_layout_value import MetaLayoutValue  # noqa: F401,E501
from photo_portfolio import util


class Layout(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, alias: str=None, value: MetaLayoutValue=None, id: int=None, is_template: bool=None):  # noqa: E501
        """Layout - a model defined in Swagger

        :param alias: The alias of this Layout.  # noqa: E501
        :type alias: str
        :param value: The value of this Layout.  # noqa: E501
        :type value: MetaLayoutValue
        :param id: The id of this Layout.  # noqa: E501
        :type id: int
        :param is_template: The is_template of this Layout.  # noqa: E501
        :type is_template: bool
        """
        self.swagger_types = {
            'alias': str,
            'value': MetaLayoutValue,
            'id': int,
            'is_template': bool
        }

        self.attribute_map = {
            'alias': 'alias',
            'value': 'value',
            'id': 'id',
            'is_template': 'is_template'
        }
        self._alias = alias
        self._value = value
        self._id = id
        self._is_template = is_template

    @classmethod
    def from_dict(cls, dikt) -> 'Layout':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Layout of this Layout.  # noqa: E501
        :rtype: Layout
        """
        return util.deserialize_model(dikt, cls)

    @property
    def alias(self) -> str:
        """Gets the alias of this Layout.


        :return: The alias of this Layout.
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias: str):
        """Sets the alias of this Layout.


        :param alias: The alias of this Layout.
        :type alias: str
        """
        if alias is None:
            raise ValueError("Invalid value for `alias`, must not be `None`")  # noqa: E501

        self._alias = alias

    @property
    def value(self) -> MetaLayoutValue:
        """Gets the value of this Layout.


        :return: The value of this Layout.
        :rtype: MetaLayoutValue
        """
        return self._value

    @value.setter
    def value(self, value: MetaLayoutValue):
        """Sets the value of this Layout.


        :param value: The value of this Layout.
        :type value: MetaLayoutValue
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def id(self) -> int:
        """Gets the id of this Layout.


        :return: The id of this Layout.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Layout.


        :param id: The id of this Layout.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def is_template(self) -> bool:
        """Gets the is_template of this Layout.


        :return: The is_template of this Layout.
        :rtype: bool
        """
        return self._is_template

    @is_template.setter
    def is_template(self, is_template: bool):
        """Sets the is_template of this Layout.


        :param is_template: The is_template of this Layout.
        :type is_template: bool
        """
        if is_template is None:
            raise ValueError("Invalid value for `is_template`, must not be `None`")  # noqa: E501

        self._is_template = is_template
