# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class MetaSubpage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, path=None, title=None, description=None):  # noqa: E501
        """MetaSubpage - a model defined in OpenAPI

        :param name: The name of this MetaSubpage.  # noqa: E501
        :type name: str
        :param path: The path of this MetaSubpage.  # noqa: E501
        :type path: str
        :param title: The title of this MetaSubpage.  # noqa: E501
        :type title: str
        :param description: The description of this MetaSubpage.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'name': str,
            'path': str,
            'title': str,
            'description': str
        }

        self.attribute_map = {
            'name': 'name',
            'path': 'path',
            'title': 'title',
            'description': 'description'
        }

        self._name = name
        self._path = path
        self._title = title
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'MetaSubpage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MetaSubpage of this MetaSubpage.  # noqa: E501
        :rtype: MetaSubpage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this MetaSubpage.


        :return: The name of this MetaSubpage.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MetaSubpage.


        :param name: The name of this MetaSubpage.
        :type name: str
        """

        self._name = name

    @property
    def path(self):
        """Gets the path of this MetaSubpage.


        :return: The path of this MetaSubpage.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this MetaSubpage.


        :param path: The path of this MetaSubpage.
        :type path: str
        """

        self._path = path

    @property
    def title(self):
        """Gets the title of this MetaSubpage.


        :return: The title of this MetaSubpage.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this MetaSubpage.


        :param title: The title of this MetaSubpage.
        :type title: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this MetaSubpage.


        :return: The description of this MetaSubpage.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this MetaSubpage.


        :param description: The description of this MetaSubpage.
        :type description: str
        """

        self._description = description
