# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Social(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, page=None, alias=None, value=None):  # noqa: E501
        """Social - a model defined in OpenAPI

        :param id: The id of this Social.  # noqa: E501
        :type id: int
        :param page: The page of this Social.  # noqa: E501
        :type page: int
        :param alias: The alias of this Social.  # noqa: E501
        :type alias: str
        :param value: The value of this Social.  # noqa: E501
        :type value: Dict[str, object]
        """
        self.openapi_types = {
            'id': int,
            'page': int,
            'alias': str,
            'value': Dict[str, object]
        }

        self.attribute_map = {
            'id': 'id',
            'page': 'page',
            'alias': 'alias',
            'value': 'value'
        }

        self._id = id
        self._page = page
        self._alias = alias
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Social':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Social of this Social.  # noqa: E501
        :rtype: Social
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Social.


        :return: The id of this Social.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Social.


        :param id: The id of this Social.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def page(self):
        """Gets the page of this Social.


        :return: The page of this Social.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this Social.


        :param page: The page of this Social.
        :type page: int
        """
        if page is None:
            raise ValueError("Invalid value for `page`, must not be `None`")  # noqa: E501

        self._page = page

    @property
    def alias(self):
        """Gets the alias of this Social.


        :return: The alias of this Social.
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this Social.


        :param alias: The alias of this Social.
        :type alias: str
        """
        if alias is None:
            raise ValueError("Invalid value for `alias`, must not be `None`")  # noqa: E501

        self._alias = alias

    @property
    def value(self):
        """Gets the value of this Social.


        :return: The value of this Social.
        :rtype: Dict[str, object]
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Social.


        :param value: The value of this Social.
        :type value: Dict[str, object]
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
