# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.meta_subpage import MetaSubpage  # noqa: F401,E501
from swagger_server import util


class SubpageIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, value: Dict=None, meta: MetaSubpage=None):  # noqa: E501
        """SubpageIdBody - a model defined in Swagger

        :param value: The value of this SubpageIdBody.  # noqa: E501
        :type value: Dict
        :param meta: The meta of this SubpageIdBody.  # noqa: E501
        :type meta: MetaSubpage
        """
        self.swagger_types = {
            'value': Dict,
            'meta': MetaSubpage
        }

        self.attribute_map = {
            'value': 'value',
            'meta': 'meta'
        }
        self._value = value
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'SubpageIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The subpage_id_body of this SubpageIdBody.  # noqa: E501
        :rtype: SubpageIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> Dict:
        """Gets the value of this SubpageIdBody.

        addtional value of subpage  # noqa: E501

        :return: The value of this SubpageIdBody.
        :rtype: Dict
        """
        return self._value

    @value.setter
    def value(self, value: Dict):
        """Sets the value of this SubpageIdBody.

        addtional value of subpage  # noqa: E501

        :param value: The value of this SubpageIdBody.
        :type value: Dict
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def meta(self) -> MetaSubpage:
        """Gets the meta of this SubpageIdBody.


        :return: The meta of this SubpageIdBody.
        :rtype: MetaSubpage
        """
        return self._meta

    @meta.setter
    def meta(self, meta: MetaSubpage):
        """Sets the meta of this SubpageIdBody.


        :param meta: The meta of this SubpageIdBody.
        :type meta: MetaSubpage
        """
        if meta is None:
            raise ValueError("Invalid value for `meta`, must not be `None`")  # noqa: E501

        self._meta = meta
